# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on: [push, pull_request]

jobs:
  Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: Docker Build
      # docker build -f x86.Dockerfile -t "neuralet/smart-social-distancing:latest-x86_64" .
      run: docker build -f x86-openvino.Dockerfile -t "neuralet/smart-social-distancing:latest-x86_64_openvino" .
    - name: Docker Run (in background)
      # docker run -d --rm -it -p HOST_PORT:8000 -v "$PWD":/repo -e TZ=`./timezone.sh` neuralet/smart-social-distancing:latest-x86_64
      run: docker run -d --rm -it -p 8400:8000 -v "$PWD":/repo  -e TZ=`./timezone.sh` neuralet/smart-social-distancing:latest-x86_64_openvino
    - name: Open interactive Bash
      run: docker exec -it $(docker ps -q) bash
    - name: Run tests
      run: pytest
    - name: Docker stop
      run: docker stop $(docker ps -q)

#
#    - name: Install dependencies
#      working-directory: ./articles
#      run: |
#        python -m pip install --upgrade pip
#        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#    - name: Create .env file
#      uses: SpicyPizza/create-envfile@v1
#      with:
#        envkey_DATABASE_ENGINE: "django.db.backends.postgresql_psycopg2"
#        envkey_DATABASE_NAME: "djangorestbase"
#        envkey_DATABASE_USER: "joaquindjango"
#        envkey_DATABASE_PASSWORD: "password"
#        envkey_DATABASE_HOST: "127.0.0.1"
#        envkey_DATABASE_PORT: 5432
#        envkey_SECRET_KEY=@_x: "lnoyv&4jv-4(h)783_y!c@!+$sxi=$(87@&sw+*z9rhd$i"
#        directory: ./articles
#        file_name: .env